#!/usr/bin/env bash
# This Bash script displays "Best School" 10 times,
# but for the 9th iteration, it displays "Best School" and "Hi" on separate lines.
i=1
while [ $i -le 10 ]
do
if [ $i -eq 9 ]; then
echo "Best School"
echo "Hi"
else
echo "Best School"
fi
((i++))
done
